modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Itamiko/EXPLOSION/issues"

[[mods]]
	modId="explosion"
	version="${file.jarVersion}"
	displayName="Explosion Explosion"
	# A URL to query for updates for this mod. See the JSON update specification <here>
	#updateJSONURL="http://myurl.me/" #optional
	displayURL="https://github.com/Itamiko/EXPLOSION"
	logoFile="megumin.png"
	authors="matsumae"
	description='''
	'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.explosion]]
	modId="forge"
	mandatory=true
	versionRange="[31,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.explosion]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.15.2]"
	ordering="NONE"
	side="BOTH"